language: node_js
node_js:
  - "9.3.0"
before_script:
  - npm run code:analysis
script:
  - npm test
  - npm run coverage:check
after_success:
  - npm run coverage:report
  - export TOOL_LIST=("TRAVIS-CI" "COVERALL" "CODECLIMATE" "DAVID-DM")
  - source <(curl -s -L $GIST_BADGE_UPDATE_SCRIPT) && source <(curl -s -L $GIST_PUSH_SCRIPT)